In [1]:
import numpy as np

In [2]:
A = np.array([
    [1,-1,2],
    [3,2,2],
    [4,1,2],
    [7,5,6]
])
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [3]:
B = np.array([
    [0, 1],
    [-1, 3],
    [5, 2]
])
B

array([[ 0,  1],
       [-1,  3],
       [ 5,  2]])

이번엔 랜덤한 값으로 행렬을 만들어보자

In [4]:
C = np.random.rand(3,5) #3행 5열
C

array([[0.65312849, 0.7294378 , 0.64990179, 0.28080705, 0.88394281],
       [0.28495995, 0.06349139, 0.58248763, 0.34148075, 0.65926429],
       [0.70233641, 0.85681414, 0.69911299, 0.64427482, 0.89907236]])

모든 값이 0인 행렬을 만들어보자

In [6]:
D = np.zeros((2,4))
D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

행렬에서 값을 받아오기를 해보자

In [8]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

1 행 3열의 값을 받아와보자

In [9]:
A[0][2]

2

크기를 벗어나는 값을 받아오려하면 어케될까?

In [10]:
A[1][3]

IndexError: index 3 is out of bounds for axis 0 with size 3

오류가 난다