In [1]:
import numpy as np

In [2]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2]
])

B = np.random.rand(3,3)

In [3]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2]])

In [4]:
B

array([[0.63166712, 0.41577235, 0.44014909],
       [0.20890157, 0.19282326, 0.99247104],
       [0.14853513, 0.171197  , 0.98629015]])

각각 3 by 3 매트릭스임

In [5]:
A + B

array([[ 1.63166712, -0.58422765,  2.44014909],
       [ 3.20890157,  2.19282326,  2.99247104],
       [ 4.14853513,  1.171197  ,  2.98629015]])

스칼라곱을 해보자

In [6]:
5 *  A

array([[ 5, -5, 10],
       [15, 10, 10],
       [20,  5, 10]])

이번엔 행렬과 행렬을 곱해보자

In [7]:
np.dot(A, B)

array([[0.71983581, 0.56534309, 1.42025834],
       [2.60987477, 1.97535757, 5.27796965],
       [3.03264032, 2.19830666, 4.72564769]])

In [8]:
A@B

array([[0.71983581, 0.56534309, 1.42025834],
       [2.60987477, 1.97535757, 5.27796965],
       [3.03264032, 2.19830666, 4.72564769]])

In [9]:
A@B + (A + 2 * B)

array([[2.98317005, 0.3968878 , 4.30055652],
       [6.02767792, 4.36100408, 9.26291174],
       [7.32971058, 3.54070066, 8.69822799]])