In [1]:
import numpy as np

In [2]:
A = np.array([
    [1, -1, 2],
    [3 ,2 ,2],
    [4, 1, 2]
])

전치행렬을 만들어보자

In [3]:
A_transpose = np.transpose(A)
A_transpose

array([[ 1,  3,  4],
       [-1,  2,  1],
       [ 2,  2,  2]])

또는

In [4]:
A.T

array([[ 1,  3,  4],
       [-1,  2,  1],
       [ 2,  2,  2]])

단위 행렬을 만들어보자

In [5]:
I_3 = np.identity(3)
I_3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

단위 행렬을 이용한 연산을 해보자

In [7]:
A @ I_3

array([[ 1., -1.,  2.],
       [ 3.,  2.,  2.],
       [ 4.,  1.,  2.]])

역행렬을 구해보자

In [9]:
A_inverse = np.linalg.pinv(A)
A_inverse

array([[-0.2, -0.4,  0.6],
       [-0.2,  0.6, -0.4],
       [ 0.5,  0.5, -0.5]])

역행렬이 없는경우도 존재한다고 앞서 배웠다 그렇다면 그때는 반환을 안할까?

아니다 최대한 비슷한것을 하는 행렬을 반환한다 제대로 나왔는제 연산을 해보자

In [10]:
A @ A_inverse

array([[ 1.00000000e+00,  6.66133815e-16, -1.11022302e-15],
       [-2.22044605e-16,  1.00000000e+00, -6.66133815e-16],
       [ 0.00000000e+00,  2.22044605e-16,  1.00000000e+00]])

대각선에는 1이 잘있다 나머지부분을 보니 e-16이란게 있는데 소수점밑으로 0이 16개 있다는 것이다 거의 0과 흡사한데 이러한 이유가 나오는 이유는 소수점을 컴퓨터가 표현하는데 문제가 있어서 그렇다