# 03 numpy array를 만드는 다양한 방법

## 1.파이썬 리스트를 통해 생성

In [2]:
import numpy

#### numpy 모듈의 array 메소드에 파라미터로 파이썬 리스트를 넘겨주면 numpy array 가 리턴됩니다.

In [3]:
array1 = numpy.array([2,3,5,7,11,13,17,19,23,29,31])
array1

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31])

## 균일한 값으로 생성


#### numpy 모듈의 full 메소드를 사용하면, 모든 값이 같은 numpy array를 생성할 수 있습니다.

In [5]:
array1 = numpy.full(6,7)    # 7의 값으로 6개요소를 가지고 있는 numpy.array를 반환한다
array1

array([7, 7, 7, 7, 7, 7])

#### 모든 값이 0인 numpy array 를만드는 아주 간단한 방법

In [10]:
array1 = numpy.full(6,0)
array2 = numpy.zeros(6, dtype = int)

In [11]:
array1

array([0, 0, 0, 0, 0, 0])

In [12]:
array2

array([0, 0, 0, 0, 0, 0])

#### 모든 값이 0인 numpy array를 만드는 아주 간단한 방법

In [3]:
array1 = numpy.full(6, 1)
array2 = numpy.ones(6, dtype=int)
array2

array([1, 1, 1, 1, 1, 1])

## 랜덤한 값들로 생성

참고로 numpy 모듈안에 random 모듈이 있고 그 안에 또 random 함수가또 있다!!

In [16]:
array1 = numpy.random.random(6)
array2 = numpy.random.random(6)

In [17]:
array1

array([0.89254544, 0.64524615, 0.10675075, 0.15925439, 0.9233811 ,
       0.39694477])

In [18]:
array2

array([0.65777723, 0.75103993, 0.56235737, 0.63555448, 0.73107326,
       0.28835035])

## 연속된 값들이 담긴 numpy array 생성

numpy 모듈의 arrange 함수를 사용하면 연속된 값들이 담겨 있는 numpy array 를 생성할 수 있습니다.

arrange 함수는 기본함수인 range 와 비슷한 원리임

### 파라미터 1개

arange(m) 을 하면 0부터 m-1 까지의 값들이 담긴 numpy array가 리턴됨

In [19]:
array1 = numpy.arange(6)
print(array1)

[0 1 2 3 4 5]


### 파라미터 2개

arange(n, m)을 하면 n 부터 m-1까지의 값들이 담긴 numpy array 가 리턴됩니다.

In [22]:
array1 = numpy.arange(2,7)
array1

array([2, 3, 4, 5, 6])

### 파라미터 3개

arrange(n, m, s)를 하면 n부터 m-1까지의 값들 중 간격이 s인 값들이 담긴 numpy array가 리턴됩니다.

In [23]:
array1 = numpy.arange(3, 17, 3)
array1

array([ 3,  6,  9, 12, 15])