# 07. 인덱싱, 슬라이싱

In [3]:
import numpy as np

In [4]:
array1 = np.array([2, 3, 4, 5, 11, 13, 17, 19, 23, 29, 31])

## 인덱싱

In [5]:
array1[0]

2

음수 인덱싱 가능

In [7]:
array1[-1]

31

In [10]:
array1[-2]

29

### 리스트로 인덱싱 하기!!

In [11]:
array1[[1,3,4]]

array([ 3,  5, 11])

### numpy array 로 인덱싱하기!!

In [25]:
array2 = np.array([2,1,3])

In [14]:
array1[array2]

array([4, 3, 5])

## 슬라이싱

2번 부터 7-1번 까지 가져와라

In [16]:
array1[2:7]

array([ 4,  5, 11, 13, 17])

0번 부터 7-1번 까지 가져와라

In [17]:
array1[:7]

array([ 2,  3,  4,  5, 11, 13, 17])

2번 이후 싹다 가져와라

In [18]:
array1[2:]

array([ 4,  5, 11, 13, 17, 19, 23, 29, 31])

2번 이후 11까지 한개 건너띄고 출력하라

In [22]:
array1[2:11:2]

array([ 4, 11, 17, 23, 31])

2번 이후 11까지 2개 건너띄고 출력하라

In [20]:
array1[2:11:3]

array([ 4, 13, 23])