# 05 numpy 기본 연산 

앞서서는 array 넣고 쓰고만 배웠었음 여기서는 연산하는것도 배울것임

In [1]:
import numpy as np

In [2]:
array1 = np.arange(10)
array2 = np.arange(10,20)

In [3]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

여기서 이제 진가를 발휘할것임

## array1 의 모든 값 2배로 곱하여 출력하기

In [5]:
array1 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

그 외의 연산

In [6]:
array1 / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [7]:
array1 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
array1 ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

#### 원본 array1 은 어떤 상태로있을까?

In [10]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

 그대로 있음

#### 만약 계산한 값의 결과를 저장하고싶다면 어케 해야하나?

In [12]:
array1 = array1 * 2

In [13]:
array1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
array1 = np.arange(10)

In [15]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

#### array1 과 array2 를 각 인덱스에 해당하는 값들을 더해보자

In [17]:
array1 + array2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

그 외의 연산

In [18]:
array1 * array2

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [19]:
array1/array2

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])