# 11. 불린 연산

In [1]:
import numpy as np

In [2]:
array1 = np.array([2,3,5,7,11,13,19,23,29,31])

numpy array 에서의 불린연산을배워보자

## 각각의 요소들이 해당하는 식에 대한 참 거짓을 출력하기

In [3]:
array1 > 4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [5]:
array1 % 2 == 0

array([ True, False, False, False, False, False, False, False, False,
       False])

## 불린 값들이 들어있는 numpy array인 booleans 를 이용한 의 불린 연산

In [6]:
booleans = np.array([True, True, False, True, True, False, True, True, True, False, True])

booleans 의 true 인 값의 인덱스만 출력하기

In [7]:
np.where(booleans)

(array([ 0,  1,  3,  4,  6,  7,  8, 10], dtype=int64),)

array1 의 4초과한 값의 인덱스를 출력하라

In [9]:
np.where(array1 > 4)

(array([2, 3, 4, 5, 6, 7, 8, 9], dtype=int64),)

array1 의 4초과한 값을 출력하라

In [12]:
filter = np.where(array1 > 4)
filter

(array([2, 3, 4, 5, 6, 7, 8, 9], dtype=int64),)

filter 에 들어있는 리스트를 이용해 값을 출력하자

In [15]:
array1[filter]

array([ 5,  7, 11, 13, 19, 23, 29, 31])